apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig 
metadata: 
   name: github-runners 
   region: us-east-1 
   version: "1.36" 

autoModeConfig: 
   enabled: true         

cloudWatch: 
   clusterLogging: 
     enableTypes: 
       - api 
       - audit 
       - authenticator 
       - controllerManager 
       - scheduler 

accessConfig: 
  authenticationMode: API_AND_CONFIG_MAP 
